name: Auto Organize Java Files

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create java folder and move Java files
        run: |
          mkdir -p java
          find . -maxdepth 1 -type f -name "*.java" -exec mv {} java/ \;

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-organize Java files"
          git push
        continue-on-error: true
